const FIREBASE_CONFIG = {
  apiKey: "AIzaSyCXi55RYsUh7ZKpyzpET_ICik2CG9rIKJQ",
  authDomain: "catchgallery.firebaseapp.com",
  databaseURL: "https://catchgallery-default-rtdb.asia-southeast1.firebasedatabase.app",
  projectId: "catchgallery",
  storageBucket: "catchgallery.firebasestorage.app",
  messagingSenderId: "184579573382",
  appId: "1:184579573382:web:c4a7d3e969b35d4065b307"
};

const WORDS = [
  ["바나나","음식"],["김밥","음식"],["떡볶이","음식"],["수박","음식"],["붕어빵","음식"],["라면","음식"],["딸기","음식"],["달걀프라이","음식"],
  ["고양이","동물"],["강아지","동물"],["기린","동물"],["토끼","동물"],["문어","동물"],["펭귄","동물"],["달팽이","동물"],["공룡","동물"],
  ["우산","물건"],["안경","물건"],["시계","물건"],["가방","물건"],["연필","물건"],["선풍기","물건"],["자전거","탈것"],["로켓","탈것"],
  ["무지개","자연"],["구름","자연"],["화산","자연"],["해바라기","자연"],["번개","자연"],["눈사람","계절"],["크리스마스트리","계절"],["수영","운동"]
];
const STATUS_LABEL = { open:"도전 중", solved:"완성", expired:"미해결", withdrawn:"회수됨" };
const appEl = document.querySelector("#app");
const headerEl = document.querySelector("#appHeader");
const scoreEl = document.querySelector("#headerScore");
const state = { user:null, isAdmin:false, authReady:false, route:"login", word:null, hintUsed:{}, galleryTab:"solved", galleryView:"frame", gallerySort:"new", galleryIndex:0, manageStatus:"open", editDrawing:null, canvas:null, ctx:null, drawing:false, dirty:false, history:[], publishing:false, feedbackView:"all", feedbackSort:"new", editingFeedback:null };
let db = null, auth = null, text = "";

function firebaseReady() { return true; }
function initFirebase() {
  if (!firebaseReady()) return false;
  if (!firebase.apps.length) firebase.initializeApp(FIREBASE_CONFIG);
  db = firebase.database(); auth = firebase.auth(); return true;
}
function serverNow() { return Date.now(); }
function escapeHtml(value="") { const d=document.createElement("div"); d.textContent=String(value); return d.innerHTML; }
function safeObject(value) { return value && typeof value === "object" ? value : {}; }
function drawerName(d){return d.drawerNickname||d.drawerDisplayName||"알 수 없음";}
function solverName(d){return d.solverNickname||d.solverDisplayName||"알 수 없음";}
function showToast(message) { const el=document.querySelector("#toast"); el.textContent=message; el.classList.add("show"); clearTimeout(showToast.timer); showToast.timer=setTimeout(()=>el.classList.remove("show"),2400); }
function loading() { appEl.innerHTML='<div class="loading" aria-label="불러오는 중"></div>'; }
function formatTime(expiresAt) { const ms=Number(expiresAt)-serverNow(); if(ms<=0)return "마감됨"; const h=Math.floor(ms/3600000); return h<1?"1시간 미만":`${h}시간`; }
function randomWord() { let next; do { next=WORDS[Math.floor(Math.random()*WORDS.length)]; } while(WORDS.length>1 && state.word?.[0]===next[0]); state.word=next; }
function isConfigured() { if(initFirebase()) return true; showToast("Firebase 설정을 먼저 연결해 주세요."); return false; }
function route(name, options={}) { state.route=name; if(name!=="draw") state.editDrawing=null; history.pushState({route:name},"",`#${name}`); renderRoute(options); }
window.addEventListener("popstate",()=>{ const name=location.hash.slice(1)|| (state.user?"home":"login"); state.route=name; renderRoute(); });
document.addEventListener("click",e=>{ const target=e.target.closest("[data-route]"); if(target) route(target.dataset.route); });
document.querySelector("#backButton").addEventListener("click",()=>history.back());

function normalizeNickname(value){return value.trim().normalize("NFC");}
function nicknameKey(value){const bytes=new TextEncoder().encode(normalizeNickname(value));return "u_"+Array.from(bytes,b=>b.toString(16).padStart(2,"0")).join("");}
function internalEmail(value){return `${nicknameKey(value)}@catchgallery.app`;}
function validateCredentials(nickname,password){const name=normalizeNickname(nickname);if(!name||name.length>8)throw new Error("닉네임은 1~8글자로 입력해 주세요.");if(password.length<6)throw new Error("비밀번호는 6자 이상 입력해 주세요.");return name;}
function authMessage(error,mode){const code=error?.code||"";if(code.includes("email-already-in-use"))return "이미 사용 중인 닉네임입니다.\n다른 닉네임을 사용해 주세요.";if(code.includes("wrong-password")||code.includes("invalid-credential")||code.includes("invalid-login-credentials"))return "비밀번호가 맞지 않습니다.";if(code.includes("user-not-found"))return "가입되지 않은 닉네임입니다.";if(code.includes("weak-password"))return "비밀번호는 6자 이상 입력해 주세요.";if(code.includes("too-many-requests"))return "잠시 후 다시 시도해 주세요.";return mode==="signup"?"회원가입 중 오류가 발생했습니다.":"로그인 중 오류가 발생했습니다.";}
async function ensureUserProfile(firebaseUser,nickname){const uid=firebaseUser.uid,key=nicknameKey(nickname),now=serverNow(),ref=db.ref(`users/${uid}`),snap=await ref.once("value"),old=snap.val();const profile=old||{nickname,nicknameKey:key,score:0,createdAt:now,rankingDeleted:false,rankingDeletedAt:null};profile.nickname=profile.nickname||nickname;profile.nicknameKey=profile.nicknameKey||key;profile.lastSeenAt=now;if(profile.rankingDeleted){profile.score=0;profile.rankingDeleted=false;profile.rankingDeletedAt=null;}await db.ref().update({[`users/${uid}`]:profile,[`nicknameIndex/${key}`]:uid});return loadCurrentUser(uid);}
async function signUp(nickname,password){const name=validateCredentials(nickname,password);localStorage.setItem("catchGalleryNickname",name);let credential;try{credential=await auth.createUserWithEmailAndPassword(internalEmail(name),password);try{await ensureUserProfile(credential.user,name);}catch(error){try{await credential.user.delete();}catch(_){}throw error;}return state.user;}catch(error){if(error.message?.startsWith("이미")||error.message?.includes("오류"))throw error;throw new Error(authMessage(error,"signup"));}}
async function signIn(nickname,password){const name=validateCredentials(nickname,password);localStorage.setItem("catchGalleryNickname",name);try{const credential=await auth.signInWithEmailAndPassword(internalEmail(name),password);await ensureUserProfile(credential.user,name);return state.user;}catch(error){if(error.message?.includes("오류"))throw error;throw new Error(authMessage(error,"login"));}}
async function signOut(){await auth.signOut();state.user=null;state.isAdmin=false;localStorage.removeItem("catchGalleryUid");localStorage.removeItem("catchGalleryNickname");route("login");}
async function boot(){initFirebase();loading();auth.onAuthStateChanged(async firebaseUser=>{try{if(firebaseUser){const saved=localStorage.getItem("catchGalleryNickname");const snap=await db.ref(`users/${firebaseUser.uid}`).once("value");if(snap.exists())await loadCurrentUser(firebaseUser.uid);else if(saved)await ensureUserProfile(firebaseUser,saved);else{await auth.signOut();throw new Error("닉네임 정보를 복구할 수 없어 다시 로그인해야 합니다.");}}else{state.user=null;state.isAdmin=false;} }catch(e){console.error(e);showToast(e.message);}state.authReady=true;const initial=state.user?(location.hash.slice(1)||"home"):"login";state.route=initial;history.replaceState({route:initial},"",`#${initial}`);renderRoute();if(state.user)expireOldDrawings().catch(console.error);});}
async function loadCurrentUser(userId=auth?.currentUser?.uid){if(!db||!userId)return null;const snap=await db.ref(`users/${userId}`).once("value");if(!snap.exists())return null;const adminSnap=await db.ref(`admins/${userId}`).once("value");state.user={id:userId,...snap.val()};state.isAdmin=adminSnap.val()===true;localStorage.setItem("catchGalleryUid",userId);localStorage.setItem("catchGalleryNickname",state.user.nickname);scoreEl.textContent=`${state.user.score||0}점`;return state.user;}

function renderRoute() {
  const publicRoute=state.route==="login";
  headerEl.classList.toggle("hidden",publicRoute);
  if(!publicRoute && !state.user){ state.route="login"; return renderLogin(); }
  ({login:renderLogin,home:renderHome,draw:renderDraw,solve:renderSolve,gallery:renderGallery,ranking:renderRanking,manage:renderManage,guide:renderGuide,feedback:renderFeedback}[state.route]||renderHome)();
}
function renderLogin() {
  appEl.innerHTML=`<section class="screen center-screen"><div class="welcome-art">🖼️</div><div style="text-align:center"><h1>캐치갤러리</h1><p class="subtitle">닉네임과 비밀번호로 시작해요!</p></div><form id="loginForm" class="card"><label class="field-label" for="nickname">닉네임</label><input id="nickname" maxlength="8" autocomplete="username" placeholder="예: 기훈" required><label class="field-label" for="password">비밀번호</label><input id="password" type="password" minlength="6" autocomplete="current-password" placeholder="6자 이상" required><p class="helper">같은 닉네임과 비밀번호로 다른 기기에서도 기록을 이어갈 수 있습니다.</p><div class="button-row"><button id="loginButton" class="button primary" type="submit">로그인</button><button id="signupButton" class="button secondary" type="button">회원가입</button></div></form></section>`;
  const form=document.querySelector("#loginForm"),nameInput=document.querySelector("#nickname"),passwordInput=document.querySelector("#password"),loginButton=document.querySelector("#loginButton"),signupButton=document.querySelector("#signupButton");nameInput.value=localStorage.getItem("catchGalleryNickname")||"";
  const submit=async mode=>{loginButton.disabled=signupButton.disabled=true;const active=mode==="login"?loginButton:signupButton,original=active.textContent;active.textContent="처리 중…";try{mode==="login"?await signIn(nameInput.value,passwordInput.value):await signUp(nameInput.value,passwordInput.value);route("home");}catch(err){showToast(err.message);}finally{loginButton.disabled=signupButton.disabled=false;active.textContent=original;}};
  form.addEventListener("submit",e=>{e.preventDefault();submit("login");});signupButton.onclick=()=>submit("signup");
}
function renderHome() {
  scoreEl.textContent=`${state.user.score||0}점`;
  appEl.innerHTML=`<section class="screen"><div class="home-greeting"><h2>${escapeHtml(state.user.nickname)}님, 반가워요!</h2><p class="muted">그림을 그리고, 다른 사람의 그림도 맞혀보세요.</p></div><div class="main-actions"><button class="main-action draw" data-route="draw"><span class="action-icon">🖍️</span><span class="action-title">그림 그리기</span><span class="action-copy">제시어를 그림으로 표현해요</span></button><button class="main-action solve" data-route="solve"><span class="action-icon">🔎</span><span class="action-title">정답 맞히기</span><span class="action-copy">이 그림은 무엇일까요?</span></button></div><div class="sub-actions"><button class="sub-action" data-route="gallery"><span>🖼️</span>전시장</button><button class="sub-action" data-route="ranking"><span>🏆</span>랭킹</button><button class="sub-action" data-route="manage"><span>📁</span>내 그림 관리</button><button class="sub-action" data-route="guide"><span>💡</span>게임설명</button><button class="sub-action feedback-menu" data-route="feedback"><span>💌</span>의견 보내기</button></div><button id="logoutButton" class="button ghost full logout-button">로그아웃</button></section>`;document.querySelector("#logoutButton").onclick=signOut;
}

function renderDraw() {
  if(!state.word) randomWord();
  const edit=state.editDrawing;
  appEl.innerHTML=`<section class="screen"><div class="section-head"><div><h2>${edit?"그림 수정하기":"그림 그리기"}</h2><p class="muted">손가락으로 마음껏 그려요.</p></div>${edit?"":'<button id="nextWord" class="button ghost">다음 제시어</button>'}</div><div class="card word-card"><span class="category">${escapeHtml(edit?.category||state.word[1])}</span><div class="word">${escapeHtml(edit?.word||state.word[0])}</div></div><div class="canvas-wrap"><canvas id="drawingCanvas" width="720" height="720" aria-label="그림판"></canvas></div><div class="tools"><div class="colors">${["#3e3a48","#ed5f72","#f29b38","#f0cf3a","#57b879","#45a8df","#745bc7"].map((c,i)=>`<button class="color ${i===0?"selected":""}" data-color="${c}" style="background:${c}" aria-label="색상 선택"></button>`).join("")}</div><div class="tool-grid"><input id="brushSize" type="range" min="3" max="34" value="9" aria-label="붓 굵기"><button id="eraser" class="button ghost">지우개</button><button id="undo" class="button ghost">되돌리기</button></div><button id="clearCanvas" class="button ghost full" style="margin-top:8px">전체 지우기</button></div><div class="notice">${edit?"수정할 때마다 최종 보상 -2점":"누군가 맞혀야 점수를 얻습니다.<br>힌트가 필요한 난해한 그림은 낮은 점수를 얻습니다."}</div><button id="saveDrawing" class="button primary full">${edit?"수정 저장하기":"게시하기"}</button></section>`;
  setupCanvas(edit?.imageData);
  document.querySelectorAll(".color").forEach(b=>b.onclick=()=>{document.querySelectorAll(".color").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");state.ctx.globalCompositeOperation="source-over";state.ctx.strokeStyle=b.dataset.color;});
  eraser.onclick=()=>{state.ctx.globalCompositeOperation="destination-out";};
  undo.onclick=undoCanvas; clearCanvas.onclick=()=>clearCanvasBoard(true);
  if(!edit) nextWord.onclick=()=>{ if(state.dirty && !confirm("그림을 지우고 다음 제시어를 받을까요?"))return; randomWord(); renderDraw(); };
  saveDrawing.onclick=async()=>{ if(!state.dirty){showToast(edit?"그림을 조금 수정해 주세요.":"빈 그림은 게시할 수 없어요.");return;} state.publishing=true;saveDrawing.disabled=true;saveDrawing.textContent="저장하는 중…";try{ edit?await updateDrawing(edit.id):await publishDrawing(); state.editDrawing=null; state.word=null; showToast(edit?"수정했어요!":"그림을 게시했어요!"); route("manage"); }catch(err){showToast(err.message);saveDrawing.disabled=false;saveDrawing.textContent=edit?"수정 저장하기":"게시하기";}finally{state.publishing=false;} };
}
function setupCanvas(imageData) {
  state.canvas=document.querySelector("#drawingCanvas"); state.ctx=state.canvas.getContext("2d",{willReadFrequently:true}); state.ctx.lineCap="round";state.ctx.lineJoin="round";state.ctx.strokeStyle="#3e3a48";state.ctx.lineWidth=9;state.history=[];state.dirty=false;
  const pos=e=>{const r=state.canvas.getBoundingClientRect(),p=e.touches?.[0]||e;return [(p.clientX-r.left)*state.canvas.width/r.width,(p.clientY-r.top)*state.canvas.height/r.height];};
  const start=e=>{e.preventDefault();saveHistory();state.drawing=true;const [x,y]=pos(e);state.ctx.beginPath();state.ctx.moveTo(x,y);};
  const move=e=>{if(!state.drawing)return;e.preventDefault();const[x,y]=pos(e);state.ctx.lineWidth=Number(brushSize.value);state.ctx.lineTo(x,y);state.ctx.stroke();state.dirty=true;};
  const end=e=>{if(state.drawing)e.preventDefault();state.drawing=false;state.ctx.closePath();};
  ["pointerdown"].forEach(n=>state.canvas.addEventListener(n,start));["pointermove"].forEach(n=>state.canvas.addEventListener(n,move));["pointerup","pointercancel","pointerleave"].forEach(n=>state.canvas.addEventListener(n,end));
  if(imageData){const img=new Image();img.onload=()=>{state.ctx.drawImage(img,0,0,720,720);};img.src=imageData;}
}
function saveHistory(){if(state.history.length>=15)state.history.shift();state.history.push(state.ctx.getImageData(0,0,state.canvas.width,state.canvas.height));}
function undoCanvas(){const last=state.history.pop();if(!last)return showToast("되돌릴 내용이 없어요.");state.ctx.globalCompositeOperation="source-over";state.ctx.putImageData(last,0,0);state.dirty=true;}
function clearCanvasBoard(track){if(track)saveHistory();state.ctx.clearRect(0,0,720,720);state.dirty=!!track;}
async function publishDrawing(){if(state.publishing===false)throw new Error("다시 시도해 주세요.");const now=serverNow(),ref=db.ref("drawings").push(),id=ref.key;const data={word:state.word[0],category:state.word[1],imageData:state.canvas.toDataURL("image/png"),drawerId:state.user.id,drawerNickname:state.user.nickname,status:"open",createdAt:now,updatedAt:now,expiresAt:now+48*3600000,revisionCount:0,solverId:null,solverNickname:null,solvedAt:null,hintUsed:false,solverReward:0,drawerReward:0,expiredAt:null,withdrawnAt:null,likeCount:0};await db.ref().update({[`drawings/${id}`]:data,[`userDrawings/${state.user.id}/${id}`]:true});state.word=null;}

async function expireOldDrawings(){if(!db)return;const snap=await db.ref("drawings").orderByChild("status").equalTo("open").once("value"),jobs=[];snap.forEach(child=>{const d=child.val();if(!d.solverId && Number(d.expiresAt)<=serverNow())jobs.push(child.ref.transaction(cur=>cur&&cur.status==="open"&&!cur.solverId&&Number(cur.expiresAt)<=serverNow()?{...cur,status:"expired",expiredAt:serverNow(),updatedAt:serverNow()}:undefined));});await Promise.all(jobs);}
async function loadOpenDrawings(sort="new"){await expireOldDrawings();const snap=await db.ref("drawings").orderByChild("status").equalTo("open").once("value");const list=[];snap.forEach(c=>{const d=c.val();if(Number(d.expiresAt)>serverNow())list.push({id:c.key,...d});});return list.sort((a,b)=>sort==="new"?b.createdAt-a.createdAt:a.createdAt-b.createdAt);}
async function renderSolve(){if(!isConfigured()){appEl.innerHTML='<section class="screen"><div class="empty">Firebase 설정을 연결해 주세요.</div></section>';return;}loading();const sort=sessionStorage.getItem("solveSort")||"new";try{const list=await loadOpenDrawings(sort);appEl.innerHTML=`<section class="screen"><div class="section-head"><div><h2>정답 맞히기</h2><p class="muted">그림 속 제시어를 찾아보세요!</p></div></div><div class="filters"><select id="solveSort"><option value="new" ${sort==="new"?"selected":""}>최신순</option><option value="old" ${sort==="old"?"selected":""}>과거순</option></select></div><div class="notice">힌트를 보면 정답 시 6점<br>힌트 없이 맞히면 10점</div><div id="openList">${list.length?list.map(openDrawingCard).join(""):emptyHtml("🧩","아직 도전할 그림이 없어요.")}</div></section>`;solveSort.onchange=()=>{sessionStorage.setItem("solveSort",solveSort.value);renderSolve();};document.querySelectorAll("[data-hint]").forEach(b=>b.onclick=()=>{state.hintUsed[b.dataset.hint]=true;b.textContent=`카테고리: ${b.dataset.category}`;b.disabled=true;});document.querySelectorAll("[data-answer-form]").forEach(f=>f.onsubmit=async e=>{e.preventDefault();const id=f.dataset.answerForm,btn=f.querySelector("button"),input=f.querySelector("input");btn.disabled=true;try{const result=await submitAnswer(id,input.value,!!state.hintUsed[id]);if(result.correct){showToast(`정답! ${result.solverReward}점을 받았어요 🎉`);await loadCurrentUser();renderSolve();}else{showToast(result.message);input.select();btn.disabled=false;}}catch(err){showToast(err.message);btn.disabled=false;}});}catch(e){console.error(e);appEl.innerHTML=`<section class="screen">${emptyHtml("😵","그림을 불러오지 못했어요.")}</section>`;}}
function openDrawingCard(d){const mine=d.drawerId===state.user.id;return `<article class="card drawing-card"><img src="${d.imageData}" alt="${escapeHtml(drawerName(d))}님의 그림"><div class="meta"><span class="badge open">남은 시간: ${formatTime(d.expiresAt)}</span><span>그린 사람: ${escapeHtml(drawerName(d))}</span></div>${mine?'<div class="notice">내 그림은 맞힐 수 없습니다.</div>':`<button class="button secondary full" data-hint="${d.id}" data-category="${escapeHtml(d.category)}">카테고리 힌트 보기</button><form class="answer-row" data-answer-form="${d.id}"><input maxlength="30" autocomplete="off" placeholder="정답을 입력해요" aria-label="정답"><button class="button primary">정답!</button></form>`}</article>`;}
async function submitAnswer(drawingId,answer,hintUsed){answer=answer.trim();if(!answer)return {correct:false,message:"정답을 입력해 주세요."};let outcome={correct:false,message:"아쉽지만 정답이 아니에요."};const now=serverNow();const result=await db.ref().transaction(root=>{if(!root)return;const d=root.drawings?.[drawingId];if(!d){outcome.message="그림을 찾을 수 없어요.";return;}if(d.drawerId===state.user.id){outcome.message="내 그림은 맞힐 수 없습니다.";return;}if(d.status!=="open"||d.solverId){outcome.message="이미 도전이 끝난 그림이에요.";return;}if(Number(d.expiresAt)<=now){d.status="expired";d.expiredAt=now;d.updatedAt=now;outcome.message="방금 마감된 그림이에요.";return root;}if(answer!==String(d.word).trim())return;const base=hintUsed?6:10,drawerReward=Math.max(0,base-(Number(d.revisionCount)||0)*2);d.status="solved";d.solverId=state.user.id;d.solverNickname=state.user.nickname;d.solvedAt=now;d.updatedAt=now;d.hintUsed=hintUsed;d.solverReward=base;d.drawerReward=drawerReward;root.users=root.users||{};if(!root.users[state.user.id])return;root.users[state.user.id].score=(Number(root.users[state.user.id].score)||0)+base;if(root.users[d.drawerId])root.users[d.drawerId].score=(Number(root.users[d.drawerId].score)||0)+drawerReward;root.userSolved=root.userSolved||{};root.userSolved[state.user.id]=root.userSolved[state.user.id]||{};root.userSolved[state.user.id][drawingId]=true;outcome={correct:true,solverReward:base,drawerReward};return root;},{applyLocally:false});if(!result.committed&&outcome.correct)return {correct:false,message:"다른 사람이 먼저 맞혔어요."};return outcome;}

async function updateDrawing(drawingId){const imageData=state.canvas.toDataURL("image/png"),now=serverNow();let reason="수정할 수 없는 그림이에요.";const result=await db.ref(`drawings/${drawingId}`).transaction(d=>{if(!d)return;if(d.status!=="open"||d.drawerId!==state.user.id||d.solverId||Number(d.expiresAt)<=now)return;reason="";return {...d,imageData,updatedAt:now,revisionCount:(Number(d.revisionCount)||0)+1};},{applyLocally:false});if(!result.committed)throw new Error(reason);}
async function withdrawDrawing(drawingId){const now=serverNow();const result=await db.ref(`drawings/${drawingId}`).transaction(d=>d&&d.status==="open"&&d.drawerId===state.user.id&&!d.solverId&&Number(d.expiresAt)>now?{...d,status:"withdrawn",withdrawnAt:now,updatedAt:now}:undefined,{applyLocally:false});if(!result.committed)throw new Error("회수할 수 없는 그림이에요.");}

async function loadGalleryDrawings(status=state.galleryTab,sort=state.gallerySort){await expireOldDrawings();const snap=await db.ref("drawings").orderByChild("status").equalTo(status).once("value"),list=[];snap.forEach(c=>list.push({id:c.key,...c.val()}));const timeKey=status==="solved"?"solvedAt":"expiredAt";return list.sort((a,b)=>sort==="popular"?(b.likeCount||0)-(a.likeCount||0):sort==="new"?b[timeKey]-a[timeKey]:a[timeKey]-b[timeKey]);}
async function renderGallery(){if(!isConfigured()){appEl.innerHTML='<section class="screen"><div class="empty">Firebase 설정을 연결해 주세요.</div></section>';return;}loading();try{const list=await loadGalleryDrawings();if(state.galleryIndex>=list.length)state.galleryIndex=0;appEl.innerHTML=`<section class="screen"><h2>전시장</h2><p class="muted">그림을 감상하고 마음에 쏙 들면 좋아요!</p><div class="tabs"><button data-gallery-tab="solved" class="${state.galleryTab==="solved"?"active":""}">완성 액자</button><button data-gallery-tab="expired" class="${state.galleryTab==="expired"?"active":""}">미해결 그림</button></div><div class="gallery-controls"><div class="view-toggle"><button data-view="frame" class="${state.galleryView==="frame"?"active":""}">액자 보기</button><button data-view="thumb" class="${state.galleryView==="thumb"?"active":""}">썸네일 보기</button></div><select id="gallerySort"><option value="new" ${state.gallerySort==="new"?"selected":""}>최신순</option><option value="old" ${state.gallerySort==="old"?"selected":""}>과거순</option><option value="popular" ${state.gallerySort==="popular"?"selected":""}>인기순</option></select></div><div id="galleryContent">${list.length?(state.galleryView==="frame"?galleryFrame(list,state.galleryIndex):galleryThumbs(list)):emptyHtml("🖼️","아직 전시된 그림이 없어요.")}</div></section>`;bindGallery(list);}catch(e){console.error(e);appEl.innerHTML=`<section class="screen">${emptyHtml("😵","전시장을 불러오지 못했어요.")}</section>`;}}
function galleryFrame(list,i){const d=list[i];return `<div class="frame"><img class="frame-image" src="${d.imageData}" alt="전시 그림"></div><div class="frame-info"><button class="secret-word" data-secret>제시어 보기 👀</button><div class="meta"><span>그린 사람: ${escapeHtml(drawerName(d))}</span><span>${d.status==="solved"?`맞힌 사람: ${escapeHtml(solverName(d))}`:"맞힌 사람: 없음"}</span></div><button class="button ${d.drawerId===state.user.id?"ghost":"secondary"} full" data-like="${d.id}" ${d.drawerId===state.user.id?"disabled":""}>♡ 좋아요 ${Number(d.likeCount)||0}${d.drawerId===state.user.id?" · 내 그림":""}</button></div><div class="frame-nav"><button class="button ghost" data-prev ${i===0?"disabled":""}>이전</button><span>${i+1} / ${list.length}</span><button class="button ghost" data-next ${i===list.length-1?"disabled":""}>다음</button></div>`;}
function galleryThumbs(list){return `<div class="thumbnail-grid">${list.map((d,i)=>`<button class="thumbnail" data-thumb="${i}"><img src="${d.imageData}" alt="전시 그림"><small>♡ ${Number(d.likeCount)||0} · ${escapeHtml(drawerName(d))}</small></button>`).join("")}</div>`;}
function bindGallery(list){document.querySelectorAll("[data-gallery-tab]").forEach(b=>b.onclick=()=>{state.galleryTab=b.dataset.galleryTab;state.galleryIndex=0;renderGallery();});document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>{state.galleryView=b.dataset.view;renderGallery();});gallerySort.onchange=()=>{state.gallerySort=gallerySort.value;state.galleryIndex=0;renderGallery();};document.querySelector("[data-prev]")?.addEventListener("click",()=>{state.galleryIndex--;renderGallery();});document.querySelector("[data-next]")?.addEventListener("click",()=>{state.galleryIndex++;renderGallery();});document.querySelector("[data-secret]")?.addEventListener("click",e=>{e.currentTarget.textContent=`제시어: ${list[state.galleryIndex].word}`;});document.querySelectorAll("[data-thumb]").forEach(b=>b.onclick=()=>{state.galleryIndex=Number(b.dataset.thumb);state.galleryView="frame";renderGallery();});document.querySelector("[data-like]")?.addEventListener("click",async e=>{e.currentTarget.disabled=true;try{await toggleLike(e.currentTarget.dataset.like);renderGallery();}catch(err){showToast(err.message);e.currentTarget.disabled=false;}});}
async function toggleLike(drawingId){let message="좋아요를 바꾸지 못했어요.";const result=await db.ref().transaction(root=>{const d=root?.drawings?.[drawingId];if(!d||!["solved","expired"].includes(d.status))return;if(d.drawerId===state.user.id){message="내 그림에는 좋아요를 누를 수 없어요.";return;}root.drawingLikes=root.drawingLikes||{};root.drawingLikes[drawingId]=root.drawingLikes[drawingId]||{};const liked=!!root.drawingLikes[drawingId][state.user.id];if(liked)delete root.drawingLikes[drawingId][state.user.id];else root.drawingLikes[drawingId][state.user.id]=true;d.likeCount=Math.max(0,(Number(d.likeCount)||0)+(liked?-1:1));message=liked?"좋아요를 취소했어요.":"좋아요를 눌렀어요!";return root;},{applyLocally:false});if(!result.committed)throw new Error(message);showToast(message);}

async function loadRanking(){const snap=await db.ref("users").orderByChild("score").limitToLast(100).once("value"),list=[];snap.forEach(c=>{const u=c.val();if(!u.rankingDeleted)list.push({id:c.key,...u});});return list.sort((a,b)=>(b.score||0)-(a.score||0)||a.createdAt-b.createdAt).slice(0,30);}
async function renderRanking(){loading();try{const list=await loadRanking();appEl.innerHTML=`<section class="screen"><h2>랭킹</h2><p class="muted">상위 30명까지 보여드려요.</p><div>${list.map((u,i)=>`<div class="rank-row ${u.id===state.user.id?"mine":""}"><div class="rank-num">${i<3?["🥇","🥈","🥉"][i]:i+1}</div><div><b>${escapeHtml(u.nickname||u.displayName)}</b>${u.id===state.user.id?"<small> · 나</small>":""}</div><div class="rank-score">${Number(u.score)||0}점</div></div>`).join("")||emptyHtml("🏆","아직 랭킹이 비어 있어요.")}</div><button id="deleteRanking" class="button danger full" style="margin-top:20px">내 랭킹 삭제</button></section>`;deleteRanking.onclick=()=>confirmModal("정말 내 랭킹을 삭제할까요?","내 점수와 랭킹 기록이 사라집니다.\n하지만 이미 전시장에 올라간 그림은 삭제되지 않습니다.",async()=>{await deleteMyRanking();showToast("랭킹을 삭제했어요. 다음 로그인부터 0점으로 다시 참여해요.");await signOut();});}catch(e){console.error(e);}}
async function deleteMyRanking(){const now=serverNow();await db.ref(`users/${state.user.id}`).update({score:0,rankingDeleted:true,rankingDeletedAt:now,lastSeenAt:now});}

async function renderManage(){if(!isConfigured()){appEl.innerHTML='<section class="screen"><div class="empty">Firebase 설정을 연결해 주세요.</div></section>';return;}loading();try{await expireOldDrawings();const idsSnap=await db.ref(`userDrawings/${state.user.id}`).once("value"),ids=Object.keys(safeObject(idsSnap.val())),all=await Promise.all(ids.map(async id=>{const s=await db.ref(`drawings/${id}`).once("value");return s.exists()?{id,...s.val()}:null;})),list=all.filter(d=>d&&d.status===state.manageStatus).sort((a,b)=>b.createdAt-a.createdAt);appEl.innerHTML=`<section class="screen"><h2>내 그림 관리</h2><p class="muted">내가 그린 그림을 상태별로 모아봐요.</p><div class="tabs status-tabs">${Object.entries(STATUS_LABEL).map(([k,v])=>`<button data-status="${k}" class="${state.manageStatus===k?"active":""}">${v}</button>`).join("")}</div><div style="margin-top:15px">${list.length?list.map(manageCard).join(""):emptyHtml("📂","여기에 해당하는 그림이 없어요.")}</div></section>`;document.querySelectorAll("[data-status]").forEach(b=>b.onclick=()=>{state.manageStatus=b.dataset.status;renderManage();});document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>{const d=list.find(x=>x.id===b.dataset.edit);state.editDrawing=d;state.word=[d.word,d.category];route("draw");});document.querySelectorAll("[data-withdraw]").forEach(b=>b.onclick=()=>confirmModal("정말 이 그림을 회수할까요?","회수한 그림은 복구할 수 없고,\n전시장에도 전시되지 않습니다.",async()=>{await withdrawDrawing(b.dataset.withdraw);showToast("그림을 회수했어요.");renderManage();}));}catch(e){console.error(e);}}
function manageCard(d){return `<article class="card drawing-card"><img src="${d.imageData}" alt="내 그림"><div class="meta"><span class="badge ${d.status}">${STATUS_LABEL[d.status]}</span><span>제시어: ${escapeHtml(d.word)}</span>${d.status==="open"?`<span>남은 시간: ${formatTime(d.expiresAt)}</span><span>수정 ${Number(d.revisionCount)||0}회</span>`:""}</div>${d.status==="open"?`<div class="notice">수정할 때마다 최종 보상 -2점</div><div class="button-row"><button class="button secondary" data-edit="${d.id}">수정하기</button><button class="button danger" data-withdraw="${d.id}">회수하기</button></div>`:d.status==="solved"?`<p>맞힌 사람: <b>${escapeHtml(solverName(d))}</b><br>획득 점수: <b>${Number(d.drawerReward)||0}점</b></p>`:d.status==="expired"?"<p>아무도 맞히지 못했어요.<br>획득 점수: <b>0점</b></p>":"<p class=\"muted\">회수한 그림은 다시 복구할 수 없어요.</p>"}</article>`;}

const FEEDBACK_SORTS=[['new','최신순'],['old','과거순'],['popular','인기순'],['likes','좋아요순'],['dislikes','싫어요순']];
async function submitFeedback(content,isAnonymous,isSecret){content=content.trim();if(content.length<=5)throw new Error("조금만 더 자세히 적어주세요.");if(content.length>300)throw new Error("300자 이내로 줄여주세요.");const now=serverNow(),ref=db.ref("feedbackMeta").push(),id=ref.key,meta={createdAt:now,updatedAt:now,isAnonymous:!!isAnonymous,isSecret:!!isSecret,displayAuthor:isAnonymous?"익명":state.user.nickname,status:"open",hidden:false,deleted:false,likeCount:0,dislikeCount:0,popularityScore:0};await db.ref().update({[`feedbackMeta/${id}`]:meta,[`feedbackContent/${id}`]:{content,adminReply:null,repliedAt:null,repliedBy:null,repliedByNickname:null},[`feedbackOwners/${id}/${state.user.id}`]:true,[`userFeedback/${state.user.id}/${id}`]:true});}
async function loadFeedback(){const [metaSnap,mySnap]=await Promise.all([db.ref("feedbackMeta").once("value"),db.ref(`userFeedback/${state.user.id}`).once("value")]),mine=safeObject(mySnap.val()),items=[];const jobs=[];metaSnap.forEach(c=>{const meta={id:c.key,...c.val(),isMine:!!mine[c.key]};if(meta.deleted)return;if(state.feedbackView==="mine"&&!meta.isMine)return;if(meta.hidden&&!state.isAdmin)return;const canRead=!meta.isSecret||meta.isMine||state.isAdmin;jobs.push((async()=>{let content=null;if(canRead){try{content=(await db.ref(`feedbackContent/${meta.id}`).once("value")).val();}catch(_){content=null;}}items.push({...meta,content});})());});await Promise.all(jobs);const comparators={new:(a,b)=>b.createdAt-a.createdAt,old:(a,b)=>a.createdAt-b.createdAt,popular:(a,b)=>(b.popularityScore||0)-(a.popularityScore||0),likes:(a,b)=>(b.likeCount||0)-(a.likeCount||0),dislikes:(a,b)=>(b.dislikeCount||0)-(a.dislikeCount||0)};return items.sort(comparators[state.feedbackSort]);}
async function updateFeedback(id,content){content=content.trim();if(content.length<=5)throw new Error("조금만 더 자세히 적어주세요.");if(content.length>300)throw new Error("300자 이내로 줄여주세요.");const owner=(await db.ref(`feedbackOwners/${id}/${state.user.id}`).once("value")).val()===true;if(!owner)throw new Error("내 의견만 수정할 수 있어요.");await db.ref().update({[`feedbackContent/${id}/content`]:content,[`feedbackMeta/${id}/updatedAt`]:serverNow()});}
async function deleteFeedback(id){const owner=(await db.ref(`feedbackOwners/${id}/${state.user.id}`).once("value")).val()===true;if(!owner)throw new Error("내 의견만 삭제할 수 있어요.");await db.ref(`feedbackMeta/${id}`).update({deleted:true,deletedAt:serverNow(),updatedAt:serverNow()});}
async function toggleFeedbackReaction(id,next){let message="반응을 저장하지 못했어요.";const result=await db.ref().transaction(root=>{const meta=root?.feedbackMeta?.[id],owner=root?.feedbackOwners?.[id]?.[state.user.id];if(!meta||meta.deleted||owner){message=owner?"내 의견에는 반응할 수 없어요.":message;return;}root.feedbackReactions=root.feedbackReactions||{};root.feedbackReactions[id]=root.feedbackReactions[id]||{};const previous=root.feedbackReactions[id][state.user.id]||null;let likes=Number(meta.likeCount)||0,dislikes=Number(meta.dislikeCount)||0;if(previous==="like")likes=Math.max(0,likes-1);if(previous==="dislike")dislikes=Math.max(0,dislikes-1);if(previous===next){delete root.feedbackReactions[id][state.user.id];message="반응을 취소했어요.";}else{root.feedbackReactions[id][state.user.id]=next;if(next==="like")likes++;else dislikes++;message=next==="like"?"좋아요를 눌렀어요!":"싫어요를 눌렀어요.";}meta.likeCount=likes;meta.dislikeCount=dislikes;meta.popularityScore=likes-dislikes;return root;},{applyLocally:false});if(!result.committed)throw new Error(message);showToast(message);}
async function saveAdminReply(id,reply){if(!state.isAdmin)throw new Error("관리자만 답변할 수 있어요.");reply=reply.trim();if(!reply)throw new Error("답변 내용을 입력해 주세요.");await db.ref().update({[`feedbackContent/${id}/adminReply`]:reply,[`feedbackContent/${id}/repliedAt`]:serverNow(),[`feedbackContent/${id}/repliedBy`]:state.user.id,[`feedbackContent/${id}/repliedByNickname`]:state.user.nickname,[`feedbackMeta/${id}/status`]:"answered",[`feedbackMeta/${id}/updatedAt`]:serverNow()});}
async function toggleFeedbackHidden(id,hidden){if(!state.isAdmin)throw new Error("관리자만 관리할 수 있어요.");await db.ref(`feedbackMeta/${id}`).update({hidden,updatedAt:serverNow()});}
async function renderFeedback(){loading();try{const list=await loadFeedback(),editing=state.editingFeedback;appEl.innerHTML=`<section class="screen"><h2>의견 보내기</h2><p class="muted">게임에 바라는 점이나 불편한 점을 남겨주세요.</p><form id="feedbackForm" class="card feedback-form"><textarea id="feedbackText" maxlength="300" placeholder="의견을 적어주세요" required>${editing?escapeHtml(editing.content):""}</textarea>${editing?"":`<label class="check-row"><input id="anonymousCheck" type="checkbox"> 익명으로 올리기</label><label class="check-row"><input id="secretCheck" type="checkbox"> 비밀글로 올리기</label>`}<div class="button-row">${editing?'<button id="cancelFeedbackEdit" class="button ghost" type="button">취소</button>':""}<button class="button primary" type="submit">${editing?"수정 저장":"보내기"}</button></div></form><div class="feedback-view-tabs"><button data-feedback-view="all" class="${state.feedbackView==="all"?"active":""}">전체 글</button><button data-feedback-view="mine" class="${state.feedbackView==="mine"?"active":""}">내 글</button></div><div class="feedback-sorts">${FEEDBACK_SORTS.map(([key,label])=>`<button data-feedback-sort="${key}" class="${state.feedbackSort===key?"active":""}">${label}</button>`).join("")}</div><div>${list.length?list.map(feedbackCard).join(""):emptyHtml("💌","아직 의견이 없어요.")}</div></section>`;bindFeedback(list);}catch(e){console.error(e);appEl.innerHTML=`<section class="screen">${emptyHtml("😵","의견을 불러오지 못했어요.")}</section>`;}}
function feedbackCard(f){const secretLocked=f.isSecret&&!f.content,body=secretLocked?'<div class="secret-feedback">🔒 비밀글입니다.<br><span>운영자와 작성자만 내용을 볼 수 있습니다.</span></div>':`<p class="feedback-content">${escapeHtml(f.content?.content||"")}</p>`,reply=f.content?.adminReply?`<div class="admin-reply"><b>🎨 운영자 답변</b><p>${escapeHtml(f.content.adminReply)}</p></div>`:"";return `<article class="card feedback-card ${f.hidden?"is-hidden":""}"><div class="feedback-head"><b>${f.isSecret?"🔒 ":""}${escapeHtml(f.displayAuthor)}</b><span>${f.status==="answered"?"답변 완료":"답변 대기"}${f.hidden?" · 숨김":""}</span></div>${body}${reply}<div class="reaction-row"><button data-react="like" data-id="${f.id}" ${f.isMine?"disabled":""}>👍 ${Number(f.likeCount)||0}</button><button data-react="dislike" data-id="${f.id}" ${f.isMine?"disabled":""}>👎 ${Number(f.dislikeCount)||0}</button></div>${f.isMine?`<div class="button-row compact"><button class="button ghost" data-edit-feedback="${f.id}">수정</button><button class="button danger" data-delete-feedback="${f.id}">삭제</button></div>`:""}${state.isAdmin?`<div class="admin-tools"><textarea data-reply-text="${f.id}" placeholder="운영자 답변">${escapeHtml(f.content?.adminReply||"")}</textarea><div class="button-row compact"><button class="button secondary" data-admin-reply="${f.id}">${f.content?.adminReply?"답변 수정":"답변하기"}</button><button class="button ghost" data-admin-hide="${f.id}" data-hidden="${f.hidden}">${f.hidden?"다시 보이기":"숨기기"}</button></div></div>`:""}</article>`;}
function bindFeedback(list){const form=document.querySelector("#feedbackForm");form.onsubmit=async e=>{e.preventDefault();const button=e.submitter;text=feedbackText.value;button.disabled=true;try{if(state.editingFeedback)await updateFeedback(state.editingFeedback.id,text);else await submitFeedback(text,anonymousCheck.checked,secretCheck.checked);state.editingFeedback=null;showToast("의견을 저장했어요.");renderFeedback();}catch(err){showToast(err.message);button.disabled=false;}};document.querySelector("#cancelFeedbackEdit")?.addEventListener("click",()=>{state.editingFeedback=null;renderFeedback();});document.querySelectorAll("[data-feedback-view]").forEach(b=>b.onclick=()=>{state.feedbackView=b.dataset.feedbackView;state.editingFeedback=null;renderFeedback();});document.querySelectorAll("[data-feedback-sort]").forEach(b=>b.onclick=()=>{state.feedbackSort=b.dataset.feedbackSort;renderFeedback();});document.querySelectorAll("[data-react]").forEach(b=>b.onclick=async()=>{b.disabled=true;try{await toggleFeedbackReaction(b.dataset.id,b.dataset.react);renderFeedback();}catch(err){showToast(err.message);b.disabled=false;}});document.querySelectorAll("[data-edit-feedback]").forEach(b=>b.onclick=()=>{const f=list.find(x=>x.id===b.dataset.editFeedback);state.editingFeedback={id:f.id,content:f.content?.content||""};renderFeedback();});document.querySelectorAll("[data-delete-feedback]").forEach(b=>b.onclick=()=>confirmModal("의견을 삭제할까요?","삭제한 의견은 목록에서 보이지 않습니다.",async()=>{await deleteFeedback(b.dataset.deleteFeedback);showToast("의견을 삭제했어요.");renderFeedback();}));document.querySelectorAll("[data-admin-reply]").forEach(b=>b.onclick=async()=>{b.disabled=true;try{await saveAdminReply(b.dataset.adminReply,document.querySelector(`[data-reply-text="${b.dataset.adminReply}"]`).value);showToast("답변을 저장했어요.");renderFeedback();}catch(err){showToast(err.message);b.disabled=false;}});document.querySelectorAll("[data-admin-hide]").forEach(b=>b.onclick=async()=>{b.disabled=true;try{await toggleFeedbackHidden(b.dataset.adminHide,b.dataset.hidden!=="true");renderFeedback();}catch(err){showToast(err.message);b.disabled=false;}});}

function renderGuide(){const items=[["캐치갤러리란?","그림을 그리고, 다른 사람이 정답을 맞히는 그림 퀴즈 게임입니다.","#ff8ea1"],["로그인","닉네임과 비밀번호로 로그인하면 다른 기기에서도 기록을 이어갈 수 있습니다.","#f0c75a"],["그림 그리기","그림은 게시만으로 점수를 얻지 않습니다. 누군가 맞혀야 점수를 얻습니다.","#73cba5"],["정답 맞히기","한 그림은 단 한 명만 맞힐 수 있습니다. 자기 그림은 맞힐 수 없습니다.","#77bfea"],["힌트와 점수","힌트 없이 맞히면 양쪽 10점, 힌트를 보면 양쪽 6점입니다. 수정한 그림은 그린 사람의 점수가 1회당 2점 줄어요.","#b59ae3"],["그림 수정·회수","도전 중인 내 그림은 수정하거나 회수할 수 있습니다. 회수하면 복구할 수 없어요.","#ffad88"],["48시간 미해결 마감","48시간 동안 아무도 못 맞히면 미해결 그림으로 전시됩니다.","#8ecbc6"],["전시장과 좋아요","완성 액자와 미해결 그림을 볼 수 있습니다. 제시어는 터치하면 공개되고, 남의 그림에 좋아요를 누를 수 있어요.","#e99ca9"],["의견 보내기","게임에 바라는 점이나 불편한 점을 익명 또는 비밀글로 남길 수 있습니다.","#79b9d3"],["랭킹 삭제","점수와 랭킹 기록은 사라지지만 이미 전시장에 올라간 그림은 그대로 남습니다.","#a9a1cf"]];appEl.innerHTML=`<section class="screen"><h2>게임설명</h2><p class="muted">알고 나면 더 재미있는 캐치갤러리!</p>${items.map(x=>`<article class="card guide-card" style="--accent:${x[2]}"><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join("")}</section>`;}
function emptyHtml(icon,text){return `<div class="empty"><div class="empty-icon">${icon}</div><p>${text}</p></div>`;}
function confirmModal(title,message,onConfirm){const root=document.querySelector("#modalRoot");root.innerHTML=`<div class="modal-backdrop"><div class="modal"><h3>${title}</h3><p>${message}</p><div class="button-row"><button class="button ghost" data-cancel>취소</button><button class="button danger" data-confirm>확인</button></div></div></div>`;root.querySelector("[data-cancel]").onclick=()=>root.innerHTML="";root.querySelector("[data-confirm]").onclick=async e=>{e.currentTarget.disabled=true;try{await onConfirm();root.innerHTML="";}catch(err){showToast(err.message);e.currentTarget.disabled=false;}};}

/* 각 레코드 단위 트랜잭션: 제한된 Rules에서도 중복 정답과 중복 반응을 막는다. */
async function submitAnswer(drawingId,answer,hintUsed){answer=answer.trim();if(!answer)return {correct:false,message:"정답을 입력해 주세요."};const now=serverNow();let outcome={correct:false,message:"아쉽지만 정답이 아니에요."},drawerId=null;const result=await db.ref(`drawings/${drawingId}`).transaction(d=>{if(!d){outcome.message="그림을 찾을 수 없어요.";return;}if(d.drawerId===state.user.id){outcome.message="내 그림은 맞힐 수 없습니다.";return;}if(d.status!=="open"||d.solverId){outcome.message="이미 도전이 끝난 그림이에요.";return;}if(Number(d.expiresAt)<=now){outcome.message="방금 마감된 그림이에요.";return {...d,status:"expired",expiredAt:now,updatedAt:now};}if(answer!==String(d.word).trim())return;const base=hintUsed?6:10,drawerReward=Math.max(0,base-(Number(d.revisionCount)||0)*2);drawerId=d.drawerId;outcome={correct:true,solverReward:base,drawerReward};return {...d,status:"solved",solverId:state.user.id,solverNickname:state.user.nickname,solvedAt:now,updatedAt:now,hintUsed,solverReward:base,drawerReward};},{applyLocally:false});if(!result.committed||!outcome.correct)return outcome.correct?{correct:false,message:"다른 사람이 먼저 맞혔어요."}:outcome;await Promise.all([db.ref(`users/${state.user.id}/score`).transaction(v=>(Number(v)||0)+outcome.solverReward),db.ref(`users/${drawerId}/score`).transaction(v=>(Number(v)||0)+outcome.drawerReward),db.ref(`userSolved/${state.user.id}/${drawingId}`).set(true)]);return outcome;}
async function toggleLike(drawingId){const drawingSnap=await db.ref(`drawings/${drawingId}`).once("value"),drawing=drawingSnap.val();if(!drawing||!["solved","expired"].includes(drawing.status))throw new Error("좋아요를 누를 수 없는 그림이에요.");if(drawing.drawerId===state.user.id)throw new Error("내 그림에는 좋아요를 누를 수 없어요.");let delta=0;const result=await db.ref(`drawingLikes/${drawingId}/${state.user.id}`).transaction(v=>{delta=v===true?-1:1;return v===true?null:true;},{applyLocally:false});if(!result.committed)throw new Error("좋아요를 바꾸지 못했어요.");await db.ref(`drawings/${drawingId}/likeCount`).transaction(v=>Math.max(0,(Number(v)||0)+delta));showToast(delta>0?"좋아요를 눌렀어요!":"좋아요를 취소했어요.");}
async function toggleFeedbackReaction(id,next){const owner=(await db.ref(`feedbackOwners/${id}/${state.user.id}`).once("value")).val()===true;if(owner)throw new Error("내 의견에는 반응할 수 없어요.");let previous=null,current=null;const result=await db.ref(`feedbackReactions/${id}/${state.user.id}`).transaction(v=>{previous=v||null;current=previous===next?null:next;return current;},{applyLocally:false});if(!result.committed)throw new Error("반응을 저장하지 못했어요.");const likeDelta=(previous==="like"?-1:0)+(current==="like"?1:0),dislikeDelta=(previous==="dislike"?-1:0)+(current==="dislike"?1:0);const metaRef=db.ref(`feedbackMeta/${id}`);await metaRef.transaction(meta=>{if(!meta||meta.deleted)return;meta.likeCount=Math.max(0,(Number(meta.likeCount)||0)+likeDelta);meta.dislikeCount=Math.max(0,(Number(meta.dislikeCount)||0)+dislikeDelta);meta.popularityScore=meta.likeCount-meta.dislikeCount;return meta;});showToast(current?`${current==="like"?"좋아요":"싫어요"}를 눌렀어요.`:"반응을 취소했어요.");}

boot();
